default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: 192.168.64.217

development:
  <<: *default
  database: standup_slackbot_development

test:
  <<: *default
  database: standup_slackbot_test
